
GET http://localhost:3000/notes

###

POST http://localhost:3000/notes HTTP/1.1
content-type: application/json

{
    "title": "Completed true",
    "description": "Lorem ipsum dolor sit amet",
    "importance": 2,
    "complete": true,
    "expire": "2020-06-08"
}

###

GET http://localhost:3000/notes/5edcbba202c4fd3461820536

###

DELETE http://localhost:3000/notes/5edcbba202c4fd3461820536

###

PATCH http://localhost:3000/notes/5edce97bcdf3d2081fe00c09 HTTP/1.1
content-type: application/json

{
    "complete": true
}