
GET http://localhost:3000/notes

###

POST http://localhost:3000/notes HTTP/1.1
content-type: application/json

{
    "title": "Bald geschafft",
    "description": "Lorem ipsum dolor sit amet",
    "importance": 5,
    "complete": false,
    "expire": "2020-08-04"
}

###

GET http://localhost:3000/notes/5edcbba202c4fd3461820536

###

DELETE http://localhost:3000/notes/5edcbba202c4fd3461820536

###

PATCH http://localhost:3000/notes/5edcbbc302c4fd3461820539 HTTP/1.1
content-type: application/json

{
    "complete": true
}